project_id = "adventure-keeper"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 15

[db.seed]
enabled = true
sql_paths = ['./seeds/*.sql']

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.external.google]
enabled = true
client_id = "env(AUTH_GOOGLE_ID)"
secret = "env(AUTH_GOOGLE_SECRET)"
skip_nonce_check = false

[auth.external.github]
enabled = true
client_id = "env(AUTH_GITHUB_ID)"
secret = "env(AUTH_GITHUB_SECRET)"
skip_nonce_check = false

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "50MiB"
