create table "public".adk_tags (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text not null,
    "slug" text not null
);


alter table "public".adk_tags enable row level security;

alter table "public"."cod_adventures" add column "long_description" text;

alter table "public"."cod_adventures" add column "max_players" smallint not null default '4'::smallint;

alter table "public"."cod_adventures" add column "session_duration" smallint not null default '2'::smallint;

alter table "public"."cod_adventures" add column tags text[];

CREATE UNIQUE INDEX tags_pkey ON public.adk_tags USING btree (id);

CREATE UNIQUE INDEX tags_slug_key ON public.adk_tags USING btree (slug);

alter table "public".adk_tags add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public".adk_tags add constraint "tags_slug_key" UNIQUE using index "tags_slug_key";

grant delete on table "public".adk_tags to "anon";

grant insert on table "public".adk_tags to "anon";

grant references on table "public".adk_tags to "anon";

grant select on table "public".adk_tags to "anon";

grant trigger on table "public".adk_tags to "anon";

grant truncate on table "public".adk_tags to "anon";

grant update on table "public".adk_tags to "anon";

grant delete on table "public".adk_tags to "authenticated";

grant insert on table "public".adk_tags to "authenticated";

grant references on table "public".adk_tags to "authenticated";

grant select on table "public".adk_tags to "authenticated";

grant trigger on table "public".adk_tags to "authenticated";

grant truncate on table "public".adk_tags to "authenticated";

grant update on table "public".adk_tags to "authenticated";

grant delete on table "public".adk_tags to "service_role";

grant insert on table "public".adk_tags to "service_role";

grant references on table "public".adk_tags to "service_role";

grant select on table "public".adk_tags to "service_role";

grant trigger on table "public".adk_tags to "service_role";

grant truncate on table "public".adk_tags to "service_role";

grant update on table "public".adk_tags to "service_role";

create policy "Enable users to view tags"
on "public".adk_tags
as permissive
for select
to authenticated
using (true);