create table "public"."cod_merits" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "prerequisites" text,
    "effect" text not null,
    "level" smallint not null default '1'::smallint,
    "slug" text not null,
    "extra_info" text,
    "uniqueness_id" text
);


alter table "public"."cod_merits" enable row level security;

CREATE UNIQUE INDEX cod_merits_pkey ON public.cod_merits USING btree (id);

CREATE UNIQUE INDEX cod_merits_slug_key ON public.cod_merits USING btree (slug);

alter table "public"."cod_merits" add constraint "cod_merits_pkey" PRIMARY KEY using index "cod_merits_pkey";

alter table "public"."cod_merits" add constraint "cod_merits_slug_key" UNIQUE using index "cod_merits_slug_key";

grant delete on table "public"."cod_merits" to "anon";

grant insert on table "public"."cod_merits" to "anon";

grant references on table "public"."cod_merits" to "anon";

grant select on table "public"."cod_merits" to "anon";

grant trigger on table "public"."cod_merits" to "anon";

grant truncate on table "public"."cod_merits" to "anon";

grant update on table "public"."cod_merits" to "anon";

grant delete on table "public"."cod_merits" to "authenticated";

grant insert on table "public"."cod_merits" to "authenticated";

grant references on table "public"."cod_merits" to "authenticated";

grant select on table "public"."cod_merits" to "authenticated";

grant trigger on table "public"."cod_merits" to "authenticated";

grant truncate on table "public"."cod_merits" to "authenticated";

grant update on table "public"."cod_merits" to "authenticated";

grant delete on table "public"."cod_merits" to "service_role";

grant insert on table "public"."cod_merits" to "service_role";

grant references on table "public"."cod_merits" to "service_role";

grant select on table "public"."cod_merits" to "service_role";

grant trigger on table "public"."cod_merits" to "service_role";

grant truncate on table "public"."cod_merits" to "service_role";

grant update on table "public"."cod_merits" to "service_role";

create policy "Enable users to view merits"
on "public".cod_merits
as permissive
for select
to authenticated
using (true);