create table "public"."cod_attributes" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text not null,
    "type" text not null,
    "slug" text not null
);


alter table "public"."cod_attributes" enable row level security;

CREATE UNIQUE INDEX cod_attributes_pkey ON public.cod_attributes USING btree (id);

CREATE UNIQUE INDEX cod_attributes_slug_key ON public.cod_attributes USING btree (slug);

alter table "public"."cod_attributes" add constraint "cod_attributes_pkey" PRIMARY KEY using index "cod_attributes_pkey";

alter table "public"."cod_attributes" add constraint "cod_attributes_slug_key" UNIQUE using index "cod_attributes_slug_key";

grant delete on table "public"."cod_attributes" to "anon";

grant insert on table "public"."cod_attributes" to "anon";

grant references on table "public"."cod_attributes" to "anon";

grant select on table "public"."cod_attributes" to "anon";

grant trigger on table "public"."cod_attributes" to "anon";

grant truncate on table "public"."cod_attributes" to "anon";

grant update on table "public"."cod_attributes" to "anon";

grant delete on table "public"."cod_attributes" to "authenticated";

grant insert on table "public"."cod_attributes" to "authenticated";

grant references on table "public"."cod_attributes" to "authenticated";

grant select on table "public"."cod_attributes" to "authenticated";

grant trigger on table "public"."cod_attributes" to "authenticated";

grant truncate on table "public"."cod_attributes" to "authenticated";

grant update on table "public"."cod_attributes" to "authenticated";

grant delete on table "public"."cod_attributes" to "service_role";

grant insert on table "public"."cod_attributes" to "service_role";

grant references on table "public"."cod_attributes" to "service_role";

grant select on table "public"."cod_attributes" to "service_role";

grant trigger on table "public"."cod_attributes" to "service_role";

grant truncate on table "public"."cod_attributes" to "service_role";

grant update on table "public"."cod_attributes" to "service_role";

create policy "Enable users to view attributes"
on "public"."cod_attributes"
as permissive
for select
to authenticated
using (true);
